menu:
  Home: /
  Archives: /archives
  About: /about
  Friends: /friends

post_copyright:
  enable: true
  author: johnpoint
  copyright_text: 本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。

loading: true
totop: true
fancybox: true
sitesince: 2019
yiyan: true

widget:
  tag:
    enable: true
    count: 10
  friends:
    enable: true
    
bigimg: #首页巨幕图片
  enable: false
  background: 
  RSS: # URL
  Github: https://github.com/johnpoint #URL
  Telegram: https://t.me/joinchat/AAAAAEFqQ5REyotgNh9yXQ #URL

friends:
  pagetitle: 小伙伴们
  list:
    - title: 友链标题1
      url: /
      img: https://cdn.lvcshu.info/img/friends/any.jpg
      desc: 友链描述友链描述友链描述1
      sidebar: true
      page: true
    - title: 友链标题2
      url: /
      img: https://cdn.lvcshu.info/img/friends/any.jpg
      desc: 友链描述友链描述友链描述2
      sidebar: true
      page: true
    - title: 友链标题3
      url: /
      img: https://cdn.lvcshu.info/img/friends/any.jpg
      desc: 友链描述友链描述友链描述3
      sidebar: true
      page: true
    - title: 友链只在友链页显示
      url: /
      img: https://cdn.lvcshu.info/img/friends/any.jpg
      desc: 友链只在友链页显示的描述
      sidebar: false
      page: true
    - title: 友链只在侧栏显示
      url: /
      img: https://cdn.lvcshu.info/img/friends/any.jpg
      desc: 友链只在侧栏显示的描述
      sidebar: true
      page: false

comment:
  disqus:
    enable: false
    shortname: 
    lazyload: true
  gitalk:
    enable: true
    owner: hexo-theme-XvA
    repo: comment
    oauth:
      client_id: 50ccdea3617dc9b66b87
      client_secret: 4915cd20257dede1e085b31be8e242284fd23efd
    admin:
      - johnpoint

analytics:
  google:
    enable: false
    id: 
  LA:
    enable: false
    id: 
  busuanzi: # 不蒜子网站统计
    enable: true
    text:
      head: 你是本站第 # 描述 示例:本站访客数 Example: view
      end: 位小伙伴~ # 描述 单位 示例:人次 Example: times
      # 效果: 本站访客数 233 人次
      # effect: view 233 times

tagscloud:
  color:
    enable: false
    start: # Start color. You can use hex (#b700ff), rgba (rgba(183, 0, 255, 1)), hsla (hsla(283, 100%, 50%, 1)) or color keywords. This option only works when color is true.
    end: # End color. You can use hex (#b700ff), rgba (rgba(183, 0, 255, 1)), hsla (hsla(283, 100%, 50%, 1)) or color keywords. This option only works when color is true.
  text:
    min: 20 # 最小字体大小 Minimal font size
    max: 40 # 最大字体大小 Maximum font size
    unit: px # 字体尺寸单位 Unit of font size
    
version: 3.3.0

bigimg: #首页巨幕图片
  enable: true
  background: 
  RSS: /atom.xml # URL
  Github: https://github.com/hexo-theme-XvA #URL
  Telegram:  #URL
  Mail: 
  wikipedia:
